-- AUTO-GENERATED SEED DATA (Regex parsed)

-- INSERT courses
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Coding Language Course', 'Rapid Lang', 'Basic Language Course of your choice - 3 Months', '3 Months', '₹5,999', 'https://topmate.io/seven_oz/1980006', 'public/assets/images/img/thumb.png', '["Introduction to programming concepts","Syntax and basic constructs","Variables, data types, and operators","Control structures: loops and conditional statements","Functions and modular programming"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Rapid Lang: Intensive 3-Month Programming Course","short_desc":"Master programming fundamentals in your chosen language with hands-on projects and expert mentorship.","details":["Learn programming fundamentals in your chosen language","Hands-on projects to reinforce concepts","Expert mentorship and feedback","Structured learning path for beginners"],"why_choose_this_course":"This course is designed for beginners who want to learn programming in a structured and practical way.","certification_available":true,"certification_cost":"₹1,999","public_review":"Students consistently rate this course highly for its clarity, practical approach, and expert mentorship."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Coding Language Course', 'Data Structures and Algorithms (DSA)', 'Master core DSA concepts for coding interviews and problem solving.', '5 Months', '₹6,499', 'https://topmate.io/seven_oz/1980024', 'public/assets/images/img/thumb.png', '["Introduction to data structures (arrays, linked lists, stacks, queues)","Basic algorithms (sorting, searching)","Advanced data structures (trees, graphs)","Algorithm design techniques (greedy, etc.)"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Data Structures and Algorithms (DSA)","short_desc":"Master core DSA concepts for coding interviews and problem solving.","details":["Introduction to data structures (arrays, linked lists, stacks, queues)","Basic algorithms (sorting, searching)","Advanced data structures (trees, graphs)","Algorithm design techniques (greedy, etc.)"],"why_choose_this_course":"This course is designed for students preparing for coding interviews and those looking to strengthen their problem-solving skills.","certification_available":false,"certification_cost":"N/A","public_review":"Students find this course highly effective in building a strong foundation in DSA concepts."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Web Development', 'Basic - Rookie', 'Learn HTML and CSS fundamentals to build responsive static websites.', '2 Months', '₹5,999', 'https://topmate.io/seven_oz/1984758', 'public/assets/images/img/thumb.png', '["HTML, CSS fundamentals","Introduction to responsive design","Building static web pages"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Basic Web Development","short_desc":"Learn HTML and CSS fundamentals to build responsive static websites.","details":["HTML, CSS fundamentals","Introduction to responsive design","Building static web pages"],"why_choose_this_course":"This course is designed for beginners who want to learn the basics of web development.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its clear explanations and practical approach."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Web Development', 'Web - Diamond', 'Build dynamic frontend apps with modern JavaScript and async programming.', '4 Months', '₹21,999', 'https://topmate.io/seven_oz/1984977', 'public/assets/images/img/thumb.png', '["JavaScript fundamentals","DOM manipulation","Asynchronous programming (Promises, async/await)"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Web - Diamond","short_desc":"Build dynamic frontend apps with modern JavaScript and async programming.","details":["JavaScript fundamentals","DOM manipulation","Asynchronous programming (Promises, async/await)"],"why_choose_this_course":"This course is designed for students who have a basic understanding of frontend development and want to build more complex applications.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its practical approach and deep dive into modern JavaScript concepts."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Web Development', 'React Dom', 'Create reusable UI components and manage app state with React.', '4 Months', '₹22,999', 'https://topmate.io/seven_oz/1984978', 'public/assets/images/img/thumb.png', '["Introduction to React framework","JSX syntax and components","State management with Redux"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"React Dom","short_desc":"Create reusable UI components and manage app state with React.","details":["Introduction to React framework","JSX syntax and components","State management with Redux"],"why_choose_this_course":"This course is designed for students who want to learn React and build modern web applications.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its clear explanations and practical projects using React."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Web Development', 'MERN Stack Development', 'Develop complete web applications using MongoDB, Express, React, and Node.', '5 Months', '₹54,999', 'https://topmate.io/seven_oz/1984979', 'public/assets/images/img/thumb.png', '["MongoDB fundamentals","Express.js basics","Node.js backend development","Integration with React frontend"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"MERN Stack Development","short_desc":"Develop complete web applications using MongoDB, Express, React, and Node.","details":["MongoDB fundamentals","Express.js basics","Node.js backend development","Integration with React frontend"],"why_choose_this_course":"This course is designed for students who want to build full-stack web applications using the MERN stack.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its comprehensive coverage of the MERN stack and practical projects."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Web Development', 'Full Stack Development', 'Become a full stack developer with APIs, auth, and deployment workflows.', '8-9 Months', '₹44,999', 'https://topmate.io/seven_oz/1984980', 'public/assets/images/img/thumb.png', '["RESTful API design and implementation","Authentication and authorization","Deployment strategies and continuous integration"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Full Stack Development","short_desc":"Become a full stack developer with APIs, auth, and deployment workflows.","details":["RESTful API design and implementation","Authentication and authorization","Deployment strategies and continuous integration"],"why_choose_this_course":"This course is designed for students who want to become proficient full stack developers and learn about APIs, authentication, and deployment.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its in-depth coverage of full stack development concepts and practical approach."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Mathematical Aptitude', 'Numerical Analysis', 'Strengthen problem-solving with practical numerical computation techniques.', '1 Month', '₹1,999', 'https://topmate.io/seven_oz/1984981', 'public/assets/images/img/thumb.png', '["Numerical methods for solving equations","Interpolation and approximation techniques","Numerical differentiation and integration"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Numerical Analysis","short_desc":"Strengthen problem-solving with practical numerical computation techniques.","details":["Numerical methods for solving equations","Interpolation and approximation techniques","Numerical differentiation and integration"],"why_choose_this_course":"This course is designed for students who want to improve their mathematical problem-solving skills with practical numerical methods.","certification_available":false,"certification_cost":"N/A","public_review":"Students find this course highly effective in enhancing their numerical problem-solving abilities."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Mathematical Aptitude', 'Statistics', 'Understand probability and statistics for analytics and decision making.', '5 Months', '₹2,499', 'https://topmate.io/seven_oz/1984983', 'public/assets/images/img/thumb.png', '["Descriptive statistics (mean, median, mode)","Probability theory","Inferential statistics (Chi Square Distribution, hypothesis testing)"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Statistics","short_desc":"Understand probability and statistics for analytics and decision making.","details":["Descriptive statistics (mean, median, mode)","Probability theory","Inferential statistics (Chi Square Distribution, hypothesis testing)"],"why_choose_this_course":"This course is designed for students who want to learn the fundamentals of statistics for data analysis and informed decision making.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its clear explanations and practical approach to learning statistics."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'ML/AI', 'Machine Learning Basics', 'Start your ML journey with supervised models and evaluation basics.', '3 Months', '₹12,999', 'https://topmate.io/seven_oz/1984996', 'public/assets/images/img/thumb.png', '["Introduction to machine learning","Linear regression, logistic regression","Model evaluation and validation techniques"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Machine Learning Basics","short_desc":"Start your ML journey with supervised models and evaluation basics.","details":["Introduction to machine learning","Linear regression, logistic regression","Model evaluation and validation techniques"],"why_choose_this_course":"This course is designed for beginners who want to start learning machine learning concepts and techniques.","certification_available":true,"certification_cost":"₹1,199","public_review":"Students consistently rate this course highly for its clear explanations and practical approach to learning machine learning basics."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'ML/AI', 'Advanced Machine Learning', 'Go deeper into advanced ML algorithms and model optimization methods.', '5 Months', '₹26,999', 'https://topmate.io/seven_oz/1984997', 'public/assets/images/img/thumb.png', '["Decision trees and ensemble methods","Support Vector Machines (SVM)","Neural networks and deep learning basics"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Advanced Machine Learning","short_desc":"Go deeper into advanced ML algorithms and model optimization methods.","details":["Decision trees and ensemble methods","Support Vector Machines (SVM)","Neural networks and deep learning basics"],"why_choose_this_course":"This course is designed for students who want to go deeper into advanced machine learning algorithms and model optimization techniques.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its comprehensive coverage of advanced machine learning concepts."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'ML/AI', 'AI Development', 'Build AI-driven solutions with NLP and computer vision foundations.', '5 Months', '₹27,999', 'https://topmate.io/seven_oz/1985001', 'public/assets/images/img/thumb.png', '["Natural Language Processing (NLP) basics","Computer Vision fundamentals"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"AI Development","short_desc":"Build AI-driven solutions with NLP and computer vision foundations.","details":["Natural Language Processing (NLP) basics","Computer Vision fundamentals"],"why_choose_this_course":"This course is designed for students who want to build AI-driven solutions using NLP and computer vision techniques.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its practical approach to building AI applications."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'ML/AI', 'Machine Learning with R', 'Apply ML workflows in R for data analysis and predictive modeling.', '3 Months', '₹15,999', 'https://topmate.io/seven_oz/1985003', 'public/assets/images/img/thumb.png', '["R programming language basics","Data manipulation with tidyverse","Statistical modeling and machine learning packages"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Machine Learning with R","short_desc":"Apply ML workflows in R for data analysis and predictive modeling.","details":["R programming language basics","Data manipulation with tidyverse","Statistical modeling and machine learning packages"],"why_choose_this_course":"This course is designed for students who want to learn how to apply machine learning workflows using the R programming language.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its clear explanations and practical approach to learning machine learning with R."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'ML/AI', 'Machine Learning with Python', 'Use Python tools and frameworks to develop practical ML models.', '5 Months', '₹28,999', 'https://topmate.io/seven_oz/1985004', 'public/assets/images/img/thumb.png', '["Python libraries for data analysis (NumPy, Pandas)","Scikit-learn for machine learning","Deep learning frameworks (TensorFlow, PyTorch)"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Machine Learning with Python","short_desc":"Use Python tools and frameworks to develop practical ML models.","details":["Python libraries for data analysis (NumPy, Pandas)","Scikit-learn for machine learning","Deep learning frameworks (TensorFlow, PyTorch)"],"why_choose_this_course":"This course is designed for learners who want to build and deploy machine learning solutions using Python.","certification_available":false,"certification_cost":"N/A","public_review":"Students rate this course highly for practical coding exercises and real-world machine learning workflows."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Design', 'Graphic Design', 'Learn design fundamentals and tools to create visual assets.', '2 Months', '₹11,999', 'https://topmate.io/seven_oz/1985005', 'public/assets/images/img/thumb.png', '["Design principles and elements","Adobe Illustrator basics"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Graphic Design","short_desc":"Learn design fundamentals and tools to create visual assets.","details":["Design principles and elements","Adobe Illustrator basics"],"why_choose_this_course":"This course helps learners build strong visual design fundamentals with hands-on creative tasks.","certification_available":false,"certification_cost":"N/A","public_review":"Learners appreciate the structured approach and practical assignments for building a design portfolio."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Design', 'UI/UX Design', 'Design intuitive user interfaces and improve digital user experiences.', '2 Months', '₹12,999', 'https://topmate.io/seven_oz/1985006', 'public/assets/images/img/thumb.png', '["User interface design fundamentals","Usability principles","Prototyping tools (Adobe XD, Sketch)"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"UI/UX Design","short_desc":"Design intuitive user interfaces and improve digital user experiences.","details":["User interface design fundamentals","Usability principles","Prototyping tools (Adobe XD, Sketch)"],"why_choose_this_course":"This course is ideal for learners who want to design user-friendly and visually polished digital products.","certification_available":false,"certification_cost":"N/A","public_review":"Students highlight the project-based learning and better understanding of user-centered design practices."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Design', '3D Modeling and Animation (using Blender)', 'Create 3D models and animations using Blender from scratch.', '3 Months', '₹17,999', 'https://topmate.io/seven_oz/1985008', 'public/assets/images/img/thumb.png', '["Introduction to Blender interface","Modeling techniques","Animation principles"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"3D Modeling and Animation (using Blender)","short_desc":"Create 3D models and animations using Blender from scratch.","details":["Introduction to Blender interface","Modeling techniques","Animation principles"],"why_choose_this_course":"This course supports beginners in building 3D modeling and animation skills with step-by-step guidance.","certification_available":false,"certification_cost":"N/A","public_review":"Learners enjoy the clear Blender workflow and practical animation exercises throughout the course."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Self Enchancment Zone', 'Spoken English', 'Improve spoken English fluency, grammar, and confidence for daily use.', '12 Months', '₹4999', 'https://topmate.io/seven_oz/1985020', 'public/assets/images/img/thumb.png', '["Speaking and pronunciation basics","Grammar and sentence structure","Confidence building in speaking"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Spoken English","short_desc":"Improve spoken English fluency, grammar, and confidence for daily use.","details":["Speaking and pronunciation basics","Grammar and sentence structure","Confidence building in speaking"],"why_choose_this_course":"This course helps learners build communication confidence for academics, interviews, and daily conversations.","certification_available":false,"certification_cost":"N/A","public_review":"Students value the confidence-building activities and practical speaking sessions."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Self Enchancment Zone', 'Discord Management and Bot Management', 'Manage Discord communities, bots, and moderation effectively.', '2 Months', '₹11,999', 'https://topmate.io/seven_oz/1985021', 'public/assets/images/img/thumb.png', '["Managing Discord servers","Creating and managing bots","Server moderation and security"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Discord Management and Bot Management","short_desc":"Manage Discord communities, bots, and moderation effectively.","details":["Managing Discord servers","Creating and managing bots","Server moderation and security"],"why_choose_this_course":"This course is great for learners who want to manage online communities with automation and moderation best practices.","certification_available":false,"certification_cost":"N/A","public_review":"Learners report better server management skills and confidence in bot workflows."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Self Enchancment Zone', 'GitHub & GitLab', 'Learn version control workflows for team collaboration and projects.', '2 Months', '₹2,999', 'https://topmate.io/seven_oz/1985027', 'public/assets/images/img/thumb.png', '["Introduction to Git and GitHub","Version control basics","Collaboration workflows"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"GitHub & GitLab","short_desc":"Learn version control workflows for team collaboration and projects.","details":["Introduction to Git and GitHub","Version control basics","Collaboration workflows"],"why_choose_this_course":"This course is ideal for learners who want to collaborate efficiently and manage code changes professionally.","certification_available":false,"certification_cost":"N/A","public_review":"Learners mention strong improvement in collaborative workflows and Git confidence."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Self Enchancment Zone', 'Photoshop : Basic to Advanced', 'Master Photoshop from basics to advanced editing and compositing.', '4 Months', '₹10,999', 'https://topmate.io/seven_oz/1985055', 'public/assets/images/img/thumb.png', '["Introduction to Photoshop","Image editing and retouching","Working with layers and masks","Advanced photo manipulation techniques","Creating digital art and composites"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Photoshop : Basic to Advanced","short_desc":"Master Photoshop from basics to advanced editing and compositing.","details":["Introduction to Photoshop","Image editing and retouching","Working with layers and masks","Advanced photo manipulation techniques","Creating digital art and composites"],"why_choose_this_course":"This course is ideal for creatives who want complete Photoshop proficiency for design and editing projects.","certification_available":false,"certification_cost":"N/A","public_review":"Students love the balance of fundamentals and advanced creative editing techniques."}'::jsonb
);
INSERT INTO courses (category, name, short_desc, duration, price, link, cover_image, details, extra_details) VALUES (
'Self Enchancment Zone', 'Lightroom : Basic to Advanced', 'Edit and organize photos professionally with Lightroom workflows.', '2 Months', '₹10,999', 'https://topmate.io/seven_oz/1985056', 'public/assets/images/img/thumb.png', '["Introduction to Lightroom","Importing and organizing photos","Basic and advanced editing techniques"]'::jsonb, '{"cover":"public/assets/images/img/thumb.png","title":"Lightroom : Basic to Advanced","short_desc":"Edit and organize photos professionally with Lightroom workflows.","details":["Introduction to Lightroom","Importing and organizing photos","Basic and advanced editing techniques"],"why_choose_this_course":"This course is for learners who want efficient and professional photo editing workflows with Lightroom.","certification_available":false,"certification_cost":"N/A","public_review":"Learners appreciate the practical editing guidance and workflow-focused lessons."}'::jsonb
);

-- INSERT services
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Academics and Certification', 'Mock and Rock (Mock Exams)', '₹500 - ₹2000', 'contact.html', '["Attempt real exam-style mock tests designed around current academic and certification patterns.","Get section-wise performance breakdowns to identify weak areas, time-management gaps, and scoring trends.","Receive targeted improvement strategies and revision guidance to boost confidence before final exams."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Mock and Rock (Mock Exams)","short_desc":"Attempt real exam-style mock tests designed around current academic and certification patterns.","description":["Attempt real exam-style mock tests designed around current academic and certification patterns.","Get section-wise performance breakdowns to identify weak areas, time-management gaps, and scoring trends.","Receive targeted improvement strategies and revision guidance to boost confidence before final exams."],"why_choose_this_course":"This course is ideal for students preparing for competitive exams or certifications who want to simulate the actual test environment, identify their strengths and weaknesses, and receive actionable feedback to improve their performance before the final exam.","certification_available":false,"certification_cost":"N/A","public_review":"Students consistently rate this course highly for its in-depth coverage of mock exam preparation and practical feedback."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Academics and Certification', 'Project Documentation', '₹500 - ₹2000', 'contact.html', '["Create complete project reports with proper structure, professional language, and institution-ready formatting.","Include system architecture, flowcharts, modules, and technical explanations in a clean and readable way.","Get support for editing, proofreading, and final polishing before submission or presentation."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Project Documentation","short_desc":"Create complete project reports with proper structure, professional language, and institution-ready formatting.","description":["Create complete project reports with proper structure, professional language, and institution-ready formatting.","Include system architecture, flowcharts, modules, and technical explanations in a clean and readable way.","Get support for editing, proofreading, and final polishing before submission or presentation."],"why_choose_this_course":"This service is best for students and teams who want professionally structured, institution-ready documentation with clear technical presentation.","certification_available":false,"certification_cost":"N/A","public_review":"Users value the clarity, formatting quality, and polished final output that improves academic and project submissions."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Academics and Certification', 'Thesis Documentation', '₹2000 onwards', 'contact.html', '["Develop end-to-end thesis documents with strong research structure, clarity, and academic tone.","Apply required citation style, chapter formatting, references, and review-friendly layout standards.","Prepare a polished final version suitable for departmental evaluation, viva, and archive submission."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Thesis Documentation","short_desc":"Develop end-to-end thesis documents with strong research structure, clarity, and academic tone.","description":["Develop end-to-end thesis documents with strong research structure, clarity, and academic tone.","Apply required citation style, chapter formatting, references, and review-friendly layout standards.","Prepare a polished final version suitable for departmental evaluation, viva, and archive submission."],"why_choose_this_course":"This service is ideal for final-year scholars who need complete thesis support with academic compliance, readability, and submission-ready quality.","certification_available":false,"certification_cost":"N/A","public_review":"Learners highlight this service for reducing thesis stress and delivering well-structured, review-friendly final documents."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Web Services', 'Developer Portfolio Website', 'Rs. 4,999 - 3,50,000', 'contact.html', '["Basic: Rs. 4,999 - 9,999.","Professional: Rs. 15,000 - 30,000.","Premium: Rs. 60,000 - 1,20,000.","Enterprise: Rs. 1,80,000 - 3,50,000."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Developer Portfolio Website","short_desc":"Build a modern developer portfolio website tailored to your skills, projects, and professional brand.","description":["Basic: Rs. 4,999 - 9,999.","Professional: Rs. 15,000 - 30,000.","Premium: Rs. 60,000 - 1,20,000.","Enterprise: Rs. 1,80,000 - 3,50,000."],"why_choose_this_course":"Perfect for developers who want a strong first impression with responsive design, project highlights, and recruiter-friendly presentation.","certification_available":false,"certification_cost":"N/A","public_review":"Clients appreciate the clean UI, performance, and conversion-focused portfolio structure."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Web Services', 'IT Executive / Corporate Portfolio', 'Rs. 8,000 - 6,00,000', 'contact.html', '["Basic: Rs. 8,000 - 15,000.","Professional: Rs. 30,000 - 60,000.","Premium: Rs. 1,20,000 - 2,50,000.","Enterprise: Rs. 3,00,000 - 6,00,000."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"IT Executive / Corporate Portfolio","short_desc":"Create a premium corporate portfolio website with polished branding and stakeholder-focused messaging.","description":["Basic: Rs. 8,000 - 15,000.","Professional: Rs. 30,000 - 60,000.","Premium: Rs. 1,20,000 - 2,50,000.","Enterprise: Rs. 3,00,000 - 6,00,000."],"why_choose_this_course":"Best suited for professionals and executives who need a premium digital presence that reflects authority and credibility.","certification_available":false,"certification_cost":"N/A","public_review":"Business users rate this service highly for brand consistency, professional look, and communication clarity."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Web Services', 'Ecommerce Development', 'Rs. 20,000 - 25,00,000', 'contact.html', '["Basic: Rs. 20,000 - 40,000.","Advanced: Rs. 80,000 - 1,50,000.","Premium: Rs. 2,50,000 - 6,00,000.","Enterprise: Rs. 8,00,000 - 25,00,000."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Ecommerce Development","short_desc":"Launch an end-to-end ecommerce platform with scalable architecture, optimized checkout, and growth-ready features.","description":["Basic: Rs. 20,000 - 40,000.","Advanced: Rs. 80,000 - 1,50,000.","Premium: Rs. 2,50,000 - 6,00,000.","Enterprise: Rs. 8,00,000 - 25,00,000."],"why_choose_this_course":"Ideal for businesses planning reliable online sales with secure payment flow, catalog scalability, and conversion-focused UX.","certification_available":false,"certification_cost":"N/A","public_review":"Store owners praise this service for robust execution, smooth user journey, and measurable business outcomes."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Web Services', 'LMS Platform Development', 'Rs. 40,000 - 50,00,000', 'contact.html', '["Basic: Rs. 40,000 - 75,000.","Advanced: Rs. 1,50,000 - 3,00,000.","Premium: Rs. 5,00,000 - 12,00,000.","Enterprise: Rs. 15,00,000 - 50,00,000."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"LMS Platform Development","short_desc":"Build a complete learning management platform with course delivery, user roles, tracking, and assessment workflows.","description":["Basic: Rs. 40,000 - 75,000.","Advanced: Rs. 1,50,000 - 3,00,000.","Premium: Rs. 5,00,000 - 12,00,000.","Enterprise: Rs. 15,00,000 - 50,00,000."],"why_choose_this_course":"Recommended for educators and organizations that need a flexible, scalable LMS with strong learner and admin experiences.","certification_available":false,"certification_cost":"N/A","public_review":"Institutes report improved learner engagement and smoother content operations after deployment."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Public Commercial', 'Custom Desktop Design', '₹2000', 'contact.html', '["Design a personalized desktop setup with custom themes, widgets, icons, and wallpaper styling.","Optimize layout, color harmony, and visual hierarchy for both aesthetics and daily usability.","Get a complete look-and-feel package aligned with your workflow, personality, and device setup."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Custom Desktop Design","short_desc":"Design a personalized desktop setup with custom themes, widgets, icons, and wallpaper styling.","description":["Design a personalized desktop setup with custom themes, widgets, icons, and wallpaper styling.","Optimize layout, color harmony, and visual hierarchy for both aesthetics and daily usability.","Get a complete look-and-feel package aligned with your workflow, personality, and device setup."],"why_choose_this_course":"Great for creators and professionals who want a premium desktop experience optimized for both appearance and productivity.","certification_available":false,"certification_cost":"N/A","public_review":"Users love the personalized styling and noticeable improvement in their day-to-day visual workflow."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Public Commercial', 'Poster and Related Design', '₹500 - ₹1000', 'contact.html', '["Create eye-catching poster concepts tailored for events, campaigns, launches, and promotions.","Balance typography, visual assets, and messaging for high impact in print and digital formats.","Deliver ready-to-use design outputs optimized for social media, banners, and physical prints."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Poster and Related Design","short_desc":"Create eye-catching poster concepts tailored for events, campaigns, launches, and promotions.","description":["Create eye-catching poster concepts tailored for events, campaigns, launches, and promotions.","Balance typography, visual assets, and messaging for high impact in print and digital formats.","Deliver ready-to-use design outputs optimized for social media, banners, and physical prints."],"why_choose_this_course":"Ideal for brands and event teams looking for fast, high-impact visuals that communicate clearly across channels.","certification_available":false,"certification_cost":"N/A","public_review":"Clients consistently mention strong visual appeal, timely delivery, and platform-ready outputs."}'::jsonb
);
INSERT INTO services (category, title, price, link, description, cover_image, extra_details) VALUES (
'Public Commercial', 'Album Design', '₹2000 - ₹5000', 'contact.html', '["Build premium album layouts with consistent visual storytelling, pacing, and aesthetic continuity.","Arrange photos, titles, and decorative elements using balanced composition and clean typography.","Produce print-ready and digital-ready album files with polished finishing and professional quality."]'::jsonb, 'public/assets/images/img/thumb.png', '{"cover":"public/assets/images/img/thumb.png","title":"Album Design","short_desc":"Build premium album layouts with consistent visual storytelling, pacing, and aesthetic continuity.","description":["Build premium album layouts with consistent visual storytelling, pacing, and aesthetic continuity.","Arrange photos, titles, and decorative elements using balanced composition and clean typography.","Produce print-ready and digital-ready album files with polished finishing and professional quality."],"why_choose_this_course":"Perfect for clients who want elegant storytelling-oriented album layouts for personal, brand, or event collections.","certification_available":false,"certification_cost":"N/A","public_review":"Customers praise the premium composition style and polished final presentation in both print and digital formats."}'::jsonb
);

-- INSERT notes
INSERT INTO notes (category, title, short_desc, date, link, cover_image, extra_details) VALUES (
'Coding Language notes', 'Python CheatSheet', 'Quick reference guide for Python syntax, built-ins, and practical coding patterns.', NULL, '#topmate#Link', NULL, '{"cover":"public/assets/images/img/thumb.png","title":"Python CheatSheet","short_desc":"Quick reference guide for Python syntax, built-ins, and practical coding patterns.","description":["Quick reference guide for Python syntax, built-ins, and practical coding patterns.","Covers essential concepts like data structures, control flow, functions, and modules.","Receive targeted improvement strategies and revision guidance to boost confidence before final exams."],"why_choose_this_course":"Ideal for students seeking a concise, exam-focused resource to quickly review key Python concepts and coding patterns before their final exams.","certification_available":false,"certification_cost":"N/A","public_review":"This Python CheatSheet was a lifesaver during my exam prep! It condensed all the essential syntax and coding patterns into one easy-to-use guide. The targeted improvement strategies helped me focus on my weak areas, and I felt much more confident going into the exam. Highly recommend for any student looking for a quick review resource!"}'::jsonb
);
INSERT INTO notes (category, title, short_desc, date, link, cover_image, extra_details) VALUES (
'Coding Language notes', 'Regression Analysis Notes', 'Compact notes on core regression concepts, assumptions, metrics, and interpretation.', NULL, '#topmate#Link', NULL, '{"cover":"public/assets/images/img/thumb.png","title":"Regression Analysis Notes","short_desc":"Compact notes on core regression concepts, assumptions, metrics, and interpretation.","description":["Compact notes on core regression concepts, assumptions, metrics, and interpretation.","Covers essential concepts like linear regression, logistic regression, and model evaluation.","Receive targeted improvement strategies and revision guidance to boost confidence before final exams."],"why_choose_this_course":"Ideal for students seeking a concise, exam-focused resource to quickly review key regression analysis concepts before their final exams.","certification_available":false,"certification_cost":"N/A","public_review":"These Regression Analysis Notes were incredibly helpful during my exam prep! The concise format made it easy to review all the key concepts quickly. The targeted improvement strategies helped me identify my weak areas and focus my revision efforts more effectively. Highly recommend!"}'::jsonb
);

-- INSERT faculty
TRUNCATE TABLE faculty;
INSERT INTO faculty (name, topic, stars, link, description, cover_image, extra_details) VALUES 
('Tanushree Biswas', 'Zoology and Graphics Design', '4.5', 'https://www.linkedin.com/in/tanushree-biswas-07365432a', 'Experienced instructor with passion for teaching', '/assets/images/faculty/tanushree.png', '{"education":["B.Sc in Zoology,NSOU"],"expertise":["Graphics Design","Illustration","Adobe Creative Suite","Zoology"]}'::jsonb),
('Rajat Howlader', 'Mathematics and Statistics', '4.5', 'https://www.linkedin.com/in/rajat-howlader-516a8a317', 'Research-focused educator specializing in Mathematics and Statistics', '/assets/images/faculty/rajat.png', '{"education":["B.Sc in Statistics, CU"],"expertise":["Machine Learning","Data Analysis","Python"]}'::jsonb),
('Jayanta Dey', 'School Education', '4', 'https://www.linkedin.com/in/joyanta-dey-8b1a943b2', 'Dedicated teacher with expertise in early education and WBBSE curriculum', '/assets/images/faculty/jayanta.png', '{"education":["10 + 2 , WBBSE"],"expertise":["Mathematics","Science","WBBSE Curriculum"]}'::jsonb),
('Rahul Sen', 'School Education', '4.1', '#', 'Expert in teaching early education and WBBSE curriculum', '/assets/images/faculty/rahul.png', '{"education":["B.Com Accountancy"],"expertise":["English","Mathematics","Science","WBBSE Curriculum"]}'::jsonb),
('Priya Paul', 'English and Geography(WBBSE) ( upto class 10) and Accounts', '4.9', 'https://www.linkedin.com/in/priya-paul-71a99728a', 'Experienced educator with expertise in English, Geography for School Students and Accounts for UG students', '/assets/images/faculty/priya.png', '{"education":["M.Com (Accounting and finance)","B.Com (Accounting and finance)"],"expertise":["English","Geography","Accounts","Finance"]}'::jsonb),
('Vansh Bhatnagar', 'Automation and robotics', '4.4', 'https://www.linkedin.com/in/vansh-bhatnagar-80ab051b5', 'Expert in automation and robotics with practical industry experience', '/assets/images/faculty/vansh.png', '{"education":["B.Tech Electrical Engineering"],"expertise":["Automation","Robotics","Control Systems"]}'::jsonb),
('Payel Saha', 'School Education', '4.2', '#', 'Expert in automation and robotics with practical industry experience', '/assets/images/faculty/female.jpg', '{"education":["B.Tech Electrical Engineering"],"expertise":["Automation","Robotics","Control Systems"]}'::jsonb),
('Ritisha Dutta', 'Class 1-5 School Education', '4.6', '#', 'Expert in teaching School Education subjects', '/assets/images/faculty/female.jpg', '{"education":["B. A Journalism and mass communication"],"expertise":["English","Geography","Accounts"]}'::jsonb);

-- INSERT founders
TRUNCATE TABLE founders;
INSERT INTO founders (name, role, linkedin_url, portfolio_url, bio, cover_image, extra_details) VALUES
('Ritam Roy', 'Founder & CEO', '#', '#', 'Visionary leader dedicated to transforming education', '/assets/images/owners/Ritam.jpeg', '{"expertise":["Strategic Leadership","Business Development","Innovation"],"gamesPlayed":[{"category":"FPS","game":"Call of Duty Mobile","logoUrl":"https://www.svgrepo.com/show/515388/call-of-duty.svg","modeIcons":{"mp":"https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/intel-cards/icons/jup_icon_mode_mp_control.png","br":"https://static.wikia.nocookie.net/callofduty/images/a/a3/BattleRoyale_Logo_Warzone_MW.png"},"rankIcons":{"mpLegendary":"/assets/components/icons/mp leggy.jpeg","brLegendary":"/assets/components/icons/br leggy.jpeg"},"data":{"mpRankCurrent":"Legendary","mpLegendaries":2,"brRankCurrent":"Legendary","brLegendaries":1}}]}'::jsonb),
('Sankha Saha', 'Co-Founder & CTO', 'https://www.linkedin.com/in/sankhasaha', 'https://codrss.tech', 'Tech innovator passionate about educational technology', '/assets/images/owners/Sankha.jpeg', '{"education":["B.Sc Statistics ( CU )","M.Sc Data Science ( AUB )"],"expertise":["Technology Strategy","Product Development","Architecture"],"books":["Coffee with C"],"research":["Time Series Forecasting of High-Volatility Stock Prices for Major Technology Conglomerates: A Comparative Study Using Gated Recurrent Unit (GRU) Architectures","Democratizing Machine Learning: A Foundational Study on AutoML Frameworks for Accessible AI","Mitigating Feature Mapping and Barren Plateau Challenges in Quantum Support Vector Machines for Classical Dataset Classification"],"gamesPlayed":[{"category":"FPS","game":"Call of Duty Mobile","logoUrl":"https://www.svgrepo.com/show/515388/call-of-duty.svg","modeIcons":{"mp":"https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/intel-cards/icons/jup_icon_mode_mp_control.png","br":"https://static.wikia.nocookie.net/callofduty/images/a/a3/BattleRoyale_Logo_Warzone_MW.png"},"rankIcons":{"mpLegendary":"/assets/components/icons/mp leggy.jpeg","brLegendary":"/assets/components/icons/br leggy.jpeg"},"data":{"mpRankCurrent":"Legendary","mpLegendaries":9,"brRankCurrent":"Legendary","brLegendaries":12}},{"category":"FPS","game":"Valorant","logoUrl":"https://images.icon-icons.com/3660/PNG/512/valorant_logo_play_riot_games_icon_228477.png","rankIcons":{"peak":"https://cdn3.emoji.gg/emojis/6329-valorant-immortal-2.png","current":"https://cdn3.emoji.gg/emojis/4071-valorant-ascendant-3.png"},"data":{"serverName":"Mumbai","peakRankActSeason":"Immortal 2 #231 (Episode 8, Act 2)","currentRank":"Ascendant 3"}},{"category":"FPS","game":"Counter-Strike 2","logoUrl":"https://ih1.redbubble.net/image.4940990177.8257/raf,360x360,075,t,fafafa:ca443f4786.jpg","data":{"serverName":"India West","peakRankActSeason":"Legendary Eagle Master (Premier Season 1)","currentRank":"Legendary Eagle"}},{"category":"Sports","game":"FIFA","logoUrl":"https://vectorseek.com/wp-content/uploads/2023/06/FIFA-Mobile-Logo-Vector-01.jpg","data":{"peakOvr":154,"peakOvrSeasonYear":"Fifa Mobile (2021)","currentOvr":112}},{"category":"Strategy","game":"Chess","logoUrl":"https://www.shutterstock.com/image-vector/chess-pieces-vector-illustration-king-600nw-1940151418.jpg","data":{"peakRating":2100,"currentRating":1950}}]}'::jsonb);
